CREATE DATABASE CINEMA2
USE CINEMA2
CREATE TABLE Company(CID SMALLINT PRIMARY KEY IDENTITY(1,1),Cname Varchar(30))
CREATE TABLE Director(DID SMALLINT PRIMARY KEY IDENTITY(1,1),DName Varchar(30),Dawards Varchar(30))
CREATE TABLE Movie(MID SMALLINT PRIMARY KEY IDENTITY(1,1),MName Varchar(30),Mdate Date,DID SMALLINT REFERENCES Director(DID))
CREATE TABLE CinemaProduction(CPID SMALLINT PRIMARY KEY IDENTITY(1,1),CPName Varchar(30), MID SMALLINT REFERENCES Movie(MID))
CREATE TABLE Actor(AID SMALLINT PRIMARY KEY IDENTITY(1,1),Aname Varchar(30),Arank INT)
CREATE TABLE CinemaPActors(AID SMALLINT REFERENCES Actor(AID),CPID SMALLINT REFERENCES CinemaProduction(CPID),Entryt VARCHAR(30),PRIMARY KEY(AID,CPID))


INSERT Company VALUES('C1'),('C2')
INSERT Director VALUES ('D1',20),('D2',10)
INSERT Movie VALUES ('M1','10-03-2000',1)
INSERT CinemaProduction VALUES('CP1',1),('CP2',1)
INSERT Actor VALUES('A1',2),('A2',20),('A3',10)
INSERT CinemaPActors VALUES(1,1,'101'),(1,2,'101'),(2,1,'101')

CREATE OR ALTER VIEW uvShowall
AS
	SELECT A.Aname
	FROM Actor A
	WHERE NOT EXISTS
	(SELECT C.CPID
	FROM CinemaProduction C
	EXCEPT
	SELECT CA.CPID
	FROM CinemaPActors CA
	WHERE A.AID=CA.AID)

CREATE OR ALTER FUNCTION ufShow(@p int)
RETURNS TABLE
RETURN
	SELECT M.MName
	FROM Movie M
	WHERE EXISTS
	(SELECT CP.MID
	FROM CinemaProduction CP
	where CP.MID=1
	GROUP BY CP.MID
	HAVING COUNT(*)>@p)
	AND M.Mdate>'12-10-1990'
SELECT * FROM ufShow(1)