CREATE DATABASE WOMEN2
USE WOMEN2

CREATE TABLE Presentation(PID SMALLINT PRIMARY KEY IDENTITY(1,1),PName Varchar(30), Pcity Varchar(30))
CREATE TABLE Women(WID SMALLINT PRIMARY KEY IDENTITY(1,1),Wname VARCHAR(30),Amount int)
CREATE TABLE ShoeModel(SMID SMALLINT PRIMARY KEY IDENTITY(1,1),SMName Varchar(30), Sseason Varchar(30))
CREATE TABLE Shoe(SID SMALLINT PRIMARY KEY IDENTITY(1,1),Sprice INT,SMID SMALLINT REFERENCES ShoeModel(SMID))
CREATE TABLE WomenShoe(WID SMALLINT REFERENCES Women(WID),SID SMALLINT REFERENCES Shoe(SID),Number INT, Spent INT,PRIMARY KEY(WID,SID))
CREATE TABLE PresentationShoe(PID SMALLINT REFERENCES Presentation(PID),SID SMALLINT REFERENCES Shoe(SID),Availble INT,PRIMARY KEY(PID,SID))

INSERT Presentation Values('P1','a'),('P2','a')
INSERT Women Values('W1',100),('W2',200),('W3',300),('W4',400)
INSERT ShoeModel Values('SM1','b'),('SM2','c'),('SM3','b')
INSERT Shoe Values(100,1),(342,1),(400,2)
INSERT WomenShoe Values(1,1,8,600),(1,2,9,500),(2,1,7,400)
INSERT PresentationShoe Values(2,1,20),(2,2,30)


CREATE OR ALTER PROC uspInsert @s SMALLINT, @p VARCHAR(30), @n INT
AS
	DECLARE @pID SMALLINT=(SELECT Presentation.PID FROM Presentation WHERE Presentation.PID=@p)
	
	IF @pID IS NULL
	BEGIN
		RAISERROR('ERROR',16,1)
		RETURN -1
	END
	INSERT PresentationShoe(PID,SID,Availble) VALUES(@pID,@s,@n)

EXEC uspInsert '3','4','100'

CREATE OR ALTER VIEW uvshowall 
AS
	SELECT Women.Wname
	FROM WOMEN
	WHERE Women.WID=
	(SELECT WS.WID
	FROM WomenShoe WS
	WHERE WS.Number>8)

CREATE OR ALTER FUNCTION ufShow(@T INT)
RETURNS TABLE
RETURN
	SELECT S.SID
	FROM Shoe S,PresentationShoe PS
	WHERE PS.SID=S.SID
	GROUP BY S.SID
	HAVING COUNT(*)>@T



SELECT * FROM ufShow(1)