CREATE DATABASE Bank2

CREATE TABLE Customers(CID SMALLINT PRIMARY KEY IDENTITY(1,1),CName VARCHAR (30), CBirth Date)
CREATE TABLE Accounts(AID SMALLINT PRIMARY KEY IDENTITY(1,1),CID SMALLINT REFERENCES Customers(CID),AIBAN INT,BALANCE INT)
CREATE TABLE Cards(CardID SMALLINT PRIMARY KEY IDENTITY(1,1),CNumber INT,CCV SMALLINT,AID SMALLINT REFERENCES Accounts(AID))
CREATE TABLE ATM(ATMID SMALLINT PRIMARY KEY IDENTITY(1,1),ATMAdress Varchar(30))
CREATE TABLE Transactions(TID SMALLINT PRIMARY KEY IDENTITY(1,1),CardID SMALLINT REFERENCES Cards(CardID),SUMM INT,DATETIM DATETIME,ATMID SMALLINT REFERENCES ATM(ATMID))

CREATE OR ALTER PROC uspDelete @card INT
AS
	DECLARE @Cardid2 INT=(SELECT Cards.CardID  FROM Cards WHERE Cards.CNumber=@card)
	DELETE FROM Transactions WHERE Transactions.CardID=@Cardid2


EXEC uspDelete '100'
INSERT Customers Values('dan','12-03-1999'),('cipri','12-04-1999')
INSERT Accounts Values(1,100,3432),(2,200,5423)	
INSERT Cards Values(1005,190,1),(102,191,1)
INSERT ATM Values ('a'),('b')
INSERT Transactions Values(2,7,'12-2-2012',4),(2,7,'12-2-2012',3),(1,7,'12-2-2012',4)

CREATE OR ALTER VIEW uspshowcardnumbers
as

	SELECT C.CNumber
	FROM Cards C
	WHERE NOT EXISTS
		(SELECT A.ATMID
		FROM ATM A
		EXCEPT
		SELECT T.ATMID 
		FROM Transactions T
		WHERE C.CardID=T.CardID)
	


SELECT * FROM uspshowcardnumbers
	

SELECT *FROM Cards
SELECT *FROM Transactions
SELECT *FROM ATM


CREATE OR ALTER FUNCTION ufFunct()
RETURNS TABLE
RETURN
	SELECT C.CNumber, C.CCV
	FROM Cards C, Transactions T
	WHERE C.CardID=T.CardID
	GROUP BY C.CNumber,C.CCV
	HAVING SUM(T.SUMM)>14

select* from ufFunct()